/*
MSSV: 22127117
Họ & Tên: Lý Liên Hoa
Mã đề: 2
Vị trí: H2C5
*/

CREATE DATABASE GK_22127117
GO

USE GK_22127117
GO

CREATE TABLE KHACHSAN (
	MAKS VARCHAR(5),
	TENKS NVARCHAR(20) UNIQUE NOT NULL,
	NAMTHANHLAP INT DEFAULT YEAR(GETDATE()),
	XEPHANG INT

	CONSTRAINT PK_KHACHSAN
	PRIMARY KEY (MAKS),
	
	CONSTRAINT CK_KHACHSAN
	CHECK (XEPHANG >= 1 and XEPHANG <=5)
)

CREATE TABLE CHINHANH (
	MACN VARCHAR(5),
	MAKS VARCHAR(5),
	DIACHI NVARCHAR(50),
	SANHTIECCHINH VARCHAR(5) DEFAULT NULL

	CONSTRAINT PK_CHINHANH
	PRIMARY KEY (MACN, MAKS)
)

CREATE TABLE SANHTIEC (
	MASANH VARCHAR(5),
	MACN VARCHAR(5),
	MAKS VARCHAR(5),
	TENSANH NVARCHAR(30),
	SUCCHUA INT,
	GIATHUE INT DEFAULT 5000

	CONSTRAINT PK_SANHTIEC
	PRIMARY KEY (MASANH, MACN, MAKS),

	CONSTRAINT CK_SANHTIEC
	CHECK (SUCCHUA > 0)
)


ALTER TABLE CHINHANH
ADD
	CONSTRAINT FK_CN_KS
	FOREIGN KEY (MAKS)
	REFERENCES KHACHSAN

ALTER TABLE SANHTIEC
ADD
	CONSTRAINT FK_ST_CN
	FOREIGN KEY (MACN, MAKS)
	REFERENCES CHINHANH


INSERT KHACHSAN
VALUES
	('K1', N'Rex', 2000, 5),
	('K2', N'Sofitel', 2015, 5),
	('K3', N'Biển xanh', 2020, 3)

INSERT CHINHANH
VALUES
	('CN1', 'K1', N'118 Cách Mạng Tháng Tám, HCM', 'S003'),
	('CN2', 'K1', N'21 Đồng Khởi, HCM', null),
	('CN1', 'K2', N'889 Trần Hưng Đạo, HCM', 'S001'),
	('CN2', 'K2', N'408 Đường 3/2, HCM', 'S001')

INSERT SANHTIEC
VALUES
	('S001', 'CN1', 'K1', N'Hoa hồng', 300, 5000),
	('S002', 'CN1', 'K1', N'Sen vàng', 800, 8000),
	('S003', 'CN1', 'K1', N'Phượng hoàng', 400, 6000),
	('S001', 'CN1', 'K2', N'Silver', 250, 4000),
	('S001', 'CN2', 'K2', N'Ruby', 500, 5000)


-- Q3:
SELECT DISTINCT KS.TENKS, KS.XEPHANG
FROM KHACHSAN KS
JOIN SANHTIEC ST
ON KS.MAKS = ST.MAKS
WHERE ST.GIATHUE >= 5000 and ST.GIATHUE <= 7000

-- Q4:
SELECT KS.TENKS, CN.DIACHI
FROM KHACHSAN KS
JOIN CHINHANH CN
ON KS.MAKS = CN.MAKS
JOIN SANHTIEC ST
ON CN.MACN = ST.MACN and CN.MAKS = ST.MAKS
WHERE KS.XEPHANG < 5 

-- Q5:
SELECT KS.TENKS, COUNT(CN.MACN) AS SoLuongChiNhanh
FROM KHACHSAN KS
LEFT JOIN CHINHANH CN
ON KS.MAKS = CN.MACN
JOIN SANHTIEC ST
ON CN.MACN = ST.MACN and CN.MAKS = ST.MAKS
GROUP BY KS.TENKS, CN.MACN
HAVING MIN(ST.SUCCHUA) >= 500

