-- Truy vấn lồng ở select -from
-- Truy vấn lồng ở WHERE --> cần lọc dữ liệu từ bảng
----> Truy vấn con có thể tham gia điều kiện



-- VD: cho biết giáo viên tham gia / đề tài do nguyễn hoài an chủ nhiệm
SELECT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
WHERE TG.MADT IN (
SELECT DT.MADT
FROM DETAI DT
WHERE DT.GVCNDT IN
	(SELECT MAGV
	FROM GIAOVIEN GV
	WHERE GV.HOTEN = N'NGUYỄN HOÀI AN'))
	

----> Truy vấn con là điều kiện (THUỘC TÍNH CHA ĐƯỢC TRUY XUẤT TRONG SUB QUERY - TRUY VẪN LỒNG TƯƠNG QUAN)
SELECT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
WHERE EXISTS (
SELECT DT.MADT
FROM DETAI DT
WHERE DT.GVCNDT IN
	(SELECT MAGV
	FROM GIAOVIEN GV
	WHERE GV.HOTEN = N'NGUYỄN HOÀI AN'))


-- Truy vấn lồng ở HAVING
-- THƯỜNG DÙNG TRONG TRƯỜNG SO SÁNH GIÁ TRỊ ĐƯỢC TÍNH TOÁN
-- CÁC HÀM KẾT HỢP (SUM, COUNT, MIN, MAX, AVG)
SELECT COUNT(MAGV)
FROM GIAOVIEN GV
GROUP BY GV.MABM
HAVING COUNT (MAGV) >= ALL(SELECT COUNT(MAGV)
						   FROM GIAOVIEN GV
						   GROUP BY GV.MABM)


-- TRUY VẤN PHÉP CHIA
-- NHẬN DẠNG PHÉP CHIA: DỮ LIỆU XUẤT PHẢI THÕA TẤT CẢ 

-- XÁC ĐỊNH CÁC THÀNH PHẦN
-- 
-- KQ: CHÍNH DỮ LIỆU XUẤT
-- C: TẤT CẢ CÁI GÌ
-- CB: QUAN HỆ GIỮA KQ VÀ CHIA

---- VÍ DỤ: CHO BIẾT GIÁO VIÊN THAM GIA TẤT CẢ ĐỀ TÀI
---- KQ: GIAOVIEN(MAGV)
---- C: DETAI(MADT)
---- BC: THAMGIADT(MAGV, MADT)

-- CÁCH CÀI ĐẶT CÂU PHÉP CHIA
---- CÁCH 1: EXCEPT
---- CÁCH 2: NOT EXISTS ... NOT EXISTS
---- CÁCH 3: ĐẾM


-- CÁCH 1: EXCEPT --
SELECT KQ.*
FROM GIAOVIEN KQ
WHERE NOT EXISTS (SELECT C.MADT
                  FROM DETAI C
				  EXCEPT 
				  SELECT BC.MADT
				  FROM THAMGIADT BC
				  WHERE BC.MAGV = KQ.MAGV)


-- CÁCH 2: NOT EXISTS ... NOT EXISTS --
SELECT KQ.*
FROM GIAOVIEN KQ
WHERE NOT EXISTS (SELECT *
                  FROM DETAI C
				  WHERE NOT EXISTS(
				  SELECT BC.MADT
				  FROM THAMGIADT BC
				  WHERE BC.MAGV = KQ.MAGV AND BC.MADT = C.MADT)
				  


-- CÁCH 3: ĐẾM --
-------UNG VOI TUNG GIAO VIEN DEM SO LUONG DE TAI GV THAM GIA
-------SO SO LUONG DE TAI = SO DE THAM GIA
SELECT COUNT(DISTINCT MADT)
FROM THAMGIADT BC
WHERE BC.MADT IN(SELECT MADT
                 FROM DETAI
                 WHERE KINHPHI > 100)
GROUP BY BC.MAGV
HAVING COUNT (DISTINCT MADT) = (SELECT COUNT(MADT) FROM DETAI C
WHERE KINHPHI > 100)