/*
SELECT ...
FROM ...
WHERE <ĐIỀU KIỆN TRÊN DÒNG>
GROUP BY TTA, TTB, ...
HAVING <ĐIỀU KIỆN TRÊN NHÓM>
ORDER BY



NẾU KHÔNG XUẤT HIỆN Ở GROUP BY THÌ PHẢI XUẤT HIỆN HÀM KẾT HỢP


*/

use QLDETAI
go

select *
from THAMGIADT

-- ĐẾM SỐ LƯỢNG ĐỀ TÀI GIÁO VIÊN '001' THAM GIA
SELECT COUNT(DISTINCT MADT) sldt FROM THAMGIADT
WHERE MAGV = '001'

SELECT GV.MAGV, GV.HOTEN, COUNT(DISTINCT MADT) sldt
FROM THAMGIADT TG
JOIN GIAOVIEN GV
ON TG.MAGV = GV.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING GV.MAGV = '001'




-- ĐẾM SỐ LƯỢNG GIÁO VIÊN CỦA TỪNG BỘ MÔN, THEO GIỚI TÍNH
SELECT GV.MABM, BM.TENBM, GV.PHAI, COUNT(MAGV) AS SLGV
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
GROUP BY GV.MABM, GV.PHAI, GV.MAGV, BM.TENBM
ORDER BY(GV.MABM)




-- 
