CREATE DATABASE QLHOINGHI
GO

USE QLHOINGHI
GO


CREATE TABLE BAIBAO (
	STT INT,
	HOINGHI VARCHAR(5),
	NAMTOCHUC INT,
	LOAIBAIBAO NVARCHAR(15),
	CHUDE NVARCHAR(15)

	CONSTRAINT PK_BAIBAO
	PRIMARY KEY (STT, HOINGHI, NAMTOCHUC)
)

CREATE TABLE HOINGHI (
	MAHOINGHI VARCHAR(5),
	QUOCGIA NVARCHAR(50),
	TENHOINGHI NVARCHAR(50),
	NAMTHANHLAP INT,
	NHAXUATBAN NVARCHAR(50)

	CONSTRAINT PK_HOINGHI
	PRIMARY KEY (MAHOINGHI)
)

CREATE TABLE TOCHUC (
	HOINGHI VARCHAR(5),
	NAMTOCHUC INT,
	DIADIEM NVARCHAR (50),
	BAIBAOTIEUBIEU INT

	CONSTRAINT PK_TOCHUC
	PRIMARY KEY (HOINGHI, NAMTOCHUC)
)


ALTER TABLE BAIBAO
ADD
	CONSTRAINT FK_BB_TC
	FOREIGN KEY (HOINGHI, NAMTOCHUC)
	REFERENCES TOCHUC,

	CONSTRAINT CK_BB
	CHECK (LOAIBAIBAO = N'Toàn văn' OR LOAIBAIBAO = N'Tóm tắt')


ALTER TABLE HOINGHI
ADD
	CONSTRAINT DF_NTL
	DEFAULT YEAR(GETDATE()) FOR NAMTHANHLAP


ALTER TABLE TOCHUC
ADD
	CONSTRAINT FK_TC_HN
	FOREIGN KEY (HOINGHI)
	REFERENCES HOINGHI,

	CONSTRAINT FK_TC_BB
	FOREIGN KEY (BAIBAOTIEUBIEU, HOINGHI, NAMTOCHUC)
	REFERENCES BAIBAO,

	CONSTRAINT DF_HN
	DEFAULT NULL FOR HOINGHI,

	CONSTRAINT DF_NTC
	DEFAULT NULL FOR NAMTOCHUC 


INSERT HOINGHI
VALUES
	('CITA', N'Việt Nam', N'Công nghệ thông tin và ứng dụng', 2023, N'Giáo dục'),
	('KES', N'Hoa Kỳ', N'Tri thức và dữ liệu', 2022, N'IEEE')

INSERT TOCHUC
VALUES
	('CITA', 2023, N'Đà Nẵng, Việt Nam', NULL),
	('KES', 2022, N'Tokyo, Nhật Bản', NULL),
	('KES', 2023, N'Paris, Pháp', NULL)


INSERT BAIBAO
VALUES
	(1, 'CITA', 2023, N'Toàn văn', N'Ứng dụng'),
	(2, 'CITA', 2023, N'Tóm tắt', N'Nghiên cứu'), 
	(1, 'KES', 2022, N'Tóm tắt', N'Nghiên cứu'), 
	(1, 'KES', 2023, N'Toàn văn', N'Ứng dụng'), 
	(2, 'KES', 2023, N'Toàn văn', N'Ứng dụng')


UPDATE TOCHUC
SET BAIBAOTIEUBIEU = 2
WHERE NAMTOCHUC = 2023

UPDATE TOCHUC
SET BAIBAOTIEUBIEU = 1
WHERE NAMTOCHUC = 2022


SELECT TC.DIADIEM
FROM TOCHUC TC
JOIN HOINGHI HN
ON TC.HOINGHI = HN.MAHOINGHI
WHERE HN.TENHOINGHI = N'Tri thức và dữ liệu' and TC.NAMTOCHUC = 2023



SELECT HN.TENHOINGHI, HN.QUOCGIA
FROM HOINGHI HN
JOIN TOCHUC TC
ON HN.MAHOINGHI = TC.HOINGHI
JOIN BAIBAO BB
ON TC.HOINGHI = BB.CHUDE and TC.NAMTOCHUC = BB.NAMTOCHUC
WHERE TC.DIADIEM like '%Nhật Bản%'
	  and BB.CHUDE = N'Nghiên cứu'
	  and NOT EXISTS (
		SELECT *
		FROM BAIBAO
		WHERE BB.LOAIBAIBAO = N'Toàn văn' and BB.CHUDE = N'Ứng dụng')





SELECT HN.MAHOINGHI, HN.TENHOINGHI, TC.NAMTOCHUC, COUNT(BB.STT) AS SoLuongBaiBao
FROM HOINGHI HN
JOIN  TOCHUC TC 
ON HN.MAHOINGHI = TC.HOINGHI
LEFT JOIN BAIBAO BB 
ON TC.HOINGHI = BB.HOINGHI AND TC.NAMTOCHUC = BB.NAMTOCHUC
GROUP BY HN.MAHOINGHI, HN.TENHOINGHI, TC.NAMTOCHUC
ORDER BY HN.MAHOINGHI, TC.NAMTOCHUC;
