CREATE DATABASE DiemThamQuan
GO

USE DiemThamQuan
GO

CREATE TABLE TINHTHANH (
	QUOCGIA CHAR(5),
	MATINHTHANH CHAR(5),
	TENTT NVARCHAR(30),
	DANSO INT,
	DIENTICH FLOAT

	CONSTRAINT PK_TINHTHANH
	PRIMARY KEY (QUOCGIA, MATINHTHANH)
)

CREATE TABLE DIEMTHAMQUAN (
	MADTQ VARCHAR(10),
	TENDTQ NVARCHAR(30),
	TINHTHANH CHAR(5),
	QUOCGIA CHAR(5),
	DACDIEM NVARCHAR(50)

	CONSTRAINT PK_DIEMTHAMQUAN
	PRIMARY KEY (MADTQ)
)

CREATE TABLE QUOCGIA (
	MAQG CHAR(5),
	TENQG NVARCHAR(20),
	THUDO CHAR(5),
	DANSO INT,
	DIENTICH FLOAT

	CONSTRAINT PK_QUOCGIA
	PRIMARY KEY (MAQG)
)

ALTER TABLE TINHTHANH
ADD
	CONSTRAINT FK_TT_QG
	FOREIGN KEY (QUOCGIA)
	REFERENCES QUOCGIA

ALTER TABLE DIEMTHAMQUAN
ADD
	CONSTRAINT FK_DTQ_TT
	FOREIGN KEY (QUOCGIA, TINHTHANH)
	REFERENCES TINHTHANH

ALTER TABLE QUOCGIA
ADD
	CONSTRAINT FK_QG_TT
	FOREIGN KEY (MAQG, THUDO)
	REFERENCES TINHTHANH

INSERT QUOCGIA
VALUES
	('QG001', N'Việt Nam', null, 115000000, 331668.00),
	('QG002', N'Nhật Bản', null, 129500000, 337834.00)

INSERT TINHTHANH
VALUES
	('QG001','TT001', N'Hà Nội', 2500000, 927.39),
	('QG001','TT002', N'Huế', 5344000, 5009.00),
	('QG002','TT003', N'Tokyo', 12084000, 2187.00)


INSERT DIEMTHAMQUAN
VALUES
	('DTQ001', N'Văn Miếu', 'TT001', 'QG001', N'Di tích cổ'),
	('DTQ002', N'Hoàng Lăng', 'TT002', 'QG001', N'Di tích cổ'),
	('DTQ003', N'Tháp Tokyo', 'TT003', 'QG002', N'Công trình hiện đại')


UPDATE QUOCGIA
SET THUDO = 'TT001'
WHERE MAQG = 'QG001'

UPDATE QUOCGIA
SET THUDO = 'TT003'
WHERE MAQG = 'QG002'



SELECT DTQ.MADTQ, DTQ.TENDTQ
FROM DIEMTHAMQUAN DTQ
JOIN TINHTHANH TT
ON DTQ.TINHTHANH = TT.MATINHTHANH AND DTQ.QUOCGIA = TT.QUOCGIA
JOIN QUOCGIA QG
ON TT.QUOCGIA = QG.MAQG
WHERE TT.DIENTICH > QG.DIENTICH / 100


SELECT QG.MAQG, QG.TENQG
FROM QUOCGIA QG
JOIN TINHTHANH TT
ON QG.THUDO = TT.MATINHTHANH
GROUP BY QG.MAQG, QG.TENQG
HAVING COUNT(TT.MATINHTHANH) > 30

