CREATE DATABASE QLBH
GO
USE QLBH
/*
Các loại ràng buộc thuộc về bảng dữ liệu:
- Khóa PRIMARY(A1, A2, ...), UNIQUE(A1, A2, ...)
- Miền giá trị của 1 cột: NOT NULLM DEFAULT VAL, CHECK(EXPRESSION)
- Tham chiếu: FOREIGN KEY(X, Y) REFERENCES TAB(A1, A2) | TAB
*/




CREATE TABLE KH(
	MaKH CHAR(5) CONSTRAINT PK_KH PRIMARY KEY,
	HoTen NVARCHAR(150) NOT NULL,
	SoCCCD CHAR(12) NOT NULL CONSTRAINT UQ_KH_SoCCCC UNIQUE,
	Phai NCHAR(3) CONSTRAINT CK_KH_PHAI CHECK(PHAI = N'Nam' OR PHAI = N'Nữ'), --PHAI IN(N'Nam', N'Nữ')
	NgayTao DATE CONSTRAINT DF_KH_NgayTao DEFAULT GETDATE()
)

CREATE TABLE SP(

)